[package]
name = "slothbear-cub"
version = "0.1.0"
authors = ["Pocket Of Weird <hartzlernathan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hostname = "0.3"
pickledb = "0.4"
serde = "1.0"
